# Generated by Django 5.2.7 on 2025-11-16 12:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auditlog_alter_googlesheetdatabase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Configuration name (e.g., 'Production API', 'Staging API')", max_length=100, unique=True)),
                ('api_url', models.URLField(help_text='API endpoint URL', max_length=500)),
                ('api_key', models.CharField(blank=True, help_text='API authentication key (optional)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active')),
                ('last_tested_at', models.DateTimeField(blank=True, help_text='Last time API connection was tested', null=True)),
                ('last_test_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', help_text='Status of last connection test', max_length=20)),
                ('last_test_message', models.TextField(blank=True, help_text='Message from last connection test')),
                ('total_candidates_available', models.IntegerField(blank=True, help_text='Total candidates available in API', null=True)),
                ('total_requests', models.IntegerField(default=0, help_text='Total API requests made')),
                ('total_successful_requests', models.IntegerField(default=0, help_text='Total successful API requests')),
                ('total_failed_requests', models.IntegerField(default=0, help_text='Total failed API requests')),
                ('average_response_time_ms', models.FloatField(blank=True, help_text='Average API response time in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configurations',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MatchingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_match_percentage', models.FloatField(help_text='Minimum match percentage used', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('use_fuzzy_matching', models.BooleanField(default=True, help_text='Whether fuzzy matching was enabled')),
                ('fuzzy_threshold', models.IntegerField(default=85, help_text='Fuzzy matching threshold used', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('total_candidates_found', models.IntegerField(default=0, help_text='Total candidates found matching criteria')),
                ('average_match_percentage', models.FloatField(blank=True, help_text='Average match percentage of found candidates', null=True)),
                ('best_match_percentage', models.FloatField(blank=True, help_text='Best match percentage found', null=True)),
                ('best_match_candidate_name', models.CharField(blank=True, help_text='Name of best matching candidate', max_length=200)),
                ('api_response_time_ms', models.IntegerField(blank=True, help_text='API response time in milliseconds', null=True)),
                ('total_api_candidates', models.IntegerField(blank=True, help_text='Total candidates available in API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matching History',
                'verbose_name_plural': 'Matching Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='googlesheetdatabase',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='jobdescription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Description', 'verbose_name_plural': 'Job Descriptions'},
        ),
        migrations.RemoveIndex(
            model_name='jobdescription',
            name='base_jobdes_is_acti_4173b6_idx',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='is_active',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='best_match_percentage',
            field=models.FloatField(blank=True, help_text='Best match percentage found', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='last_matched_at',
            field=models.DateTimeField(blank=True, help_text='Last time candidates were matched', null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='total_candidates_matched',
            field=models.IntegerField(default=0, help_text='Total candidates matched across all runs'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='total_matches_run',
            field=models.IntegerField(default=0, help_text='Number of times matching was run for this JD'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='all_skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of all extracted skills'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='created_by',
            field=models.ForeignKey(help_text='User who uploaded this JD', on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='experience_level',
            field=models.CharField(blank=True, help_text='Required experience level', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='file',
            field=models.FileField(blank=True, help_text='Upload JD file (PDF, DOCX, TXT)', null=True, upload_to='jd_uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='jd_text',
            field=models.TextField(blank=True, help_text='Extracted text from JD file'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='key_responsibilities',
            field=models.TextField(blank=True, help_text='Key responsibilities from JD'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='linkedin_search_string',
            field=models.TextField(blank=True, help_text='JSON object containing various LinkedIn search strings'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='linkedin_skills_string',
            field=models.TextField(blank=True, help_text='LinkedIn-optimized skills string'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Required qualifications'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='role_category',
            field=models.CharField(blank=True, help_text='Category of role (e.g., IT, HR, Marketing)', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='skill_categories',
            field=models.JSONField(blank=True, default=dict, help_text='Skills organized by category'),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='title',
            field=models.CharField(help_text='Job title/position', max_length=200),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['-created_at'], name='base_jobdes_created_2ff248_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['role_category'], name='base_jobdes_role_ca_d7dc07_idx'),
        ),
        migrations.AddField(
            model_name='apiconfiguration',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_configurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchinghistory',
            name='job_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_history', to='base.jobdescription'),
        ),
        migrations.AddField(
            model_name='matchinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='GoogleSheetDatabase',
        ),
        migrations.AddIndex(
            model_name='matchinghistory',
            index=models.Index(fields=['-created_at'], name='base_matchi_created_8a0bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='matchinghistory',
            index=models.Index(fields=['job_description', '-created_at'], name='base_matchi_job_des_b6877f_idx'),
        ),
        migrations.AddIndex(
            model_name='matchinghistory',
            index=models.Index(fields=['user', '-created_at'], name='base_matchi_user_id_f44f1e_idx'),
        ),
    ]
